name: Docker Image vikru/location-api-server

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '0 5 4,18 * *'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: vikru/location-api-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: ${{ github.event_name != 'schedule' }}
        workdir: location_api_server
        snapshot: true