name: PlatformIO CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v1

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio

    - name: Run PlatformIO
      run: platformio run

    - name: Create date tag
      id: devtag
      run: echo "::set-output name=value::$(date +'dev-v%Y-%m-%d-%H-%M')"


    - name: Publish firmware Permanent
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .pio/build/esp32dev/firmware.bin
        asset_name: firmware.bin
        tag: ${{ steps.devtag.outputs.value  }}
        overwrite: true
        allowUpdates: true

    - name: Publish firmware Latest
      uses: svenstaro/upload-release-action@v1-release
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: .pio/build/esp07/firmware.bin
        asset_name: firmware.bin
        tag: dev
        overwrite: true
        allowUpdates: true
